// Icons exported from Figma (packages/assets/icons). Strokes are currentColor,
// so colour comes from the `color` token prop — matching how each Figma icon
// component binds its stroke to a color/icon/* variable.
// The registry is generated by scripts/write-icons.py.
import type { ColorToken } from "@vitallink/tokens";
import { ICONS } from "./icons.gen";

export type IconName = keyof typeof ICONS;

const cssVar = (t: ColorToken) => `var(--vl-${t.replace(/[A-Z]/g, (c) => "-" + c.toLowerCase())})`;
export const tokenVar = cssVar;

export function Icon({
  name,
  color = "iconDefault",
  className,
}: {
  name: IconName;
  color?: ColorToken;
  className?: string;
}) {
  const Svg = ICONS[name];
  // Width/height come from the exported file's root attributes; never overridden.
  return <Svg aria-hidden className={className} style={{ color: cssVar(color), flexShrink: 0, display: "block" }} />;
}
