// Generated by scripts/write-icons.py. Do not edit.
// Strokes are currentColor; colour comes from a token at the call site.
import Appointments16 from "../../../../packages/assets/icons/appointments-16.svg?react";
import Appointments18 from "../../../../packages/assets/icons/appointments-18.svg?react";
import Appointments20 from "../../../../packages/assets/icons/appointments-20.svg?react";
import Appointments22 from "../../../../packages/assets/icons/appointments-22.svg?react";
import Bike18 from "../../../../packages/assets/icons/bike-18.svg?react";
import Bike20 from "../../../../packages/assets/icons/bike-20.svg?react";
import Check14 from "../../../../packages/assets/icons/check-14.svg?react";
import Check16 from "../../../../packages/assets/icons/check-16.svg?react";
import ChevronLeft16 from "../../../../packages/assets/icons/chevron-left-16.svg?react";
import ChevronLeft17 from "../../../../packages/assets/icons/chevron-left-17.svg?react";
import ChevronRight16 from "../../../../packages/assets/icons/chevron-right-16.svg?react";
import ChevronRight18 from "../../../../packages/assets/icons/chevron-right-18.svg?react";
import Clock16 from "../../../../packages/assets/icons/clock-16.svg?react";
import Clock20 from "../../../../packages/assets/icons/clock-20.svg?react";
import Dashboard18 from "../../../../packages/assets/icons/dashboard-18.svg?react";
import Devices16 from "../../../../packages/assets/icons/devices-16.svg?react";
import Devices18 from "../../../../packages/assets/icons/devices-18.svg?react";
import Devices20 from "../../../../packages/assets/icons/devices-20.svg?react";
import Devices22 from "../../../../packages/assets/icons/devices-22.svg?react";
import Download16 from "../../../../packages/assets/icons/download-16.svg?react";
import Droplet18 from "../../../../packages/assets/icons/droplet-18.svg?react";
import Droplet20 from "../../../../packages/assets/icons/droplet-20.svg?react";
import Droplet22 from "../../../../packages/assets/icons/droplet-22.svg?react";
import Dumbbell16 from "../../../../packages/assets/icons/dumbbell-16.svg?react";
import Dumbbell18 from "../../../../packages/assets/icons/dumbbell-18.svg?react";
import Dumbbell20 from "../../../../packages/assets/icons/dumbbell-20.svg?react";
import Dumbbell22 from "../../../../packages/assets/icons/dumbbell-22.svg?react";
import Emergency16 from "../../../../packages/assets/icons/emergency-16.svg?react";
import Emergency18 from "../../../../packages/assets/icons/emergency-18.svg?react";
import Emergency20 from "../../../../packages/assets/icons/emergency-20.svg?react";
import Emergency22 from "../../../../packages/assets/icons/emergency-22.svg?react";
import Emergency26 from "../../../../packages/assets/icons/emergency-26.svg?react";
import Emergency28 from "../../../../packages/assets/icons/emergency-28.svg?react";
import Emergency36 from "../../../../packages/assets/icons/emergency-36.svg?react";
import Eye17 from "../../../../packages/assets/icons/eye-17.svg?react";
import Eye18 from "../../../../packages/assets/icons/eye-18.svg?react";
import Family16 from "../../../../packages/assets/icons/family-16.svg?react";
import Family18 from "../../../../packages/assets/icons/family-18.svg?react";
import Family20 from "../../../../packages/assets/icons/family-20.svg?react";
import Family22 from "../../../../packages/assets/icons/family-22.svg?react";
import FileText16 from "../../../../packages/assets/icons/file-text-16.svg?react";
import FileText18 from "../../../../packages/assets/icons/file-text-18.svg?react";
import FileText20 from "../../../../packages/assets/icons/file-text-20.svg?react";
import Flame16 from "../../../../packages/assets/icons/flame-16.svg?react";
import Goals16 from "../../../../packages/assets/icons/goals-16.svg?react";
import Goals18 from "../../../../packages/assets/icons/goals-18.svg?react";
import Goals20 from "../../../../packages/assets/icons/goals-20.svg?react";
import Health16 from "../../../../packages/assets/icons/health-16.svg?react";
import Health17 from "../../../../packages/assets/icons/health-17.svg?react";
import Health18 from "../../../../packages/assets/icons/health-18.svg?react";
import Health20 from "../../../../packages/assets/icons/health-20.svg?react";
import Health22 from "../../../../packages/assets/icons/health-22.svg?react";
import Help18 from "../../../../packages/assets/icons/help-18.svg?react";
import Home22 from "../../../../packages/assets/icons/home-22.svg?react";
import Library16 from "../../../../packages/assets/icons/library-16.svg?react";
import Library18 from "../../../../packages/assets/icons/library-18.svg?react";
import Library20 from "../../../../packages/assets/icons/library-20.svg?react";
import MapPin16 from "../../../../packages/assets/icons/map-pin-16.svg?react";
import Medications16 from "../../../../packages/assets/icons/medications-16.svg?react";
import Medications18 from "../../../../packages/assets/icons/medications-18.svg?react";
import Medications20 from "../../../../packages/assets/icons/medications-20.svg?react";
import Medications22 from "../../../../packages/assets/icons/medications-22.svg?react";
import Messages16 from "../../../../packages/assets/icons/messages-16.svg?react";
import Messages18 from "../../../../packages/assets/icons/messages-18.svg?react";
import Messages20 from "../../../../packages/assets/icons/messages-20.svg?react";
import Monitor18 from "../../../../packages/assets/icons/monitor-18.svg?react";
import Monitor20 from "../../../../packages/assets/icons/monitor-20.svg?react";
import Monitor22 from "../../../../packages/assets/icons/monitor-22.svg?react";
import Moon16 from "../../../../packages/assets/icons/moon-16.svg?react";
import Moon18 from "../../../../packages/assets/icons/moon-18.svg?react";
import Notifications16 from "../../../../packages/assets/icons/notifications-16.svg?react";
import Notifications18 from "../../../../packages/assets/icons/notifications-18.svg?react";
import Notifications20 from "../../../../packages/assets/icons/notifications-20.svg?react";
import Nutrition16 from "../../../../packages/assets/icons/nutrition-16.svg?react";
import Nutrition18 from "../../../../packages/assets/icons/nutrition-18.svg?react";
import Nutrition20 from "../../../../packages/assets/icons/nutrition-20.svg?react";
import Phone16 from "../../../../packages/assets/icons/phone-16.svg?react";
import Plus16 from "../../../../packages/assets/icons/plus-16.svg?react";
import Plus18 from "../../../../packages/assets/icons/plus-18.svg?react";
import Print16 from "../../../../packages/assets/icons/print-16.svg?react";
import Privacy16 from "../../../../packages/assets/icons/privacy-16.svg?react";
import Privacy18 from "../../../../packages/assets/icons/privacy-18.svg?react";
import Privacy20 from "../../../../packages/assets/icons/privacy-20.svg?react";
import Privacy22 from "../../../../packages/assets/icons/privacy-22.svg?react";
import Records16 from "../../../../packages/assets/icons/records-16.svg?react";
import Records18 from "../../../../packages/assets/icons/records-18.svg?react";
import Records20 from "../../../../packages/assets/icons/records-20.svg?react";
import Records22 from "../../../../packages/assets/icons/records-22.svg?react";
import Run18 from "../../../../packages/assets/icons/run-18.svg?react";
import Run20 from "../../../../packages/assets/icons/run-20.svg?react";
import Scale16 from "../../../../packages/assets/icons/scale-16.svg?react";
import Scale18 from "../../../../packages/assets/icons/scale-18.svg?react";
import Scale20 from "../../../../packages/assets/icons/scale-20.svg?react";
import Scale22 from "../../../../packages/assets/icons/scale-22.svg?react";
import Search16 from "../../../../packages/assets/icons/search-16.svg?react";
import Search17 from "../../../../packages/assets/icons/search-17.svg?react";
import Search18 from "../../../../packages/assets/icons/search-18.svg?react";
import Settings16 from "../../../../packages/assets/icons/settings-16.svg?react";
import Settings18 from "../../../../packages/assets/icons/settings-18.svg?react";
import Settings20 from "../../../../packages/assets/icons/settings-20.svg?react";
import Share16 from "../../../../packages/assets/icons/share-16.svg?react";
import ShieldCheck16 from "../../../../packages/assets/icons/shield-check-16.svg?react";
import ShieldCheck20 from "../../../../packages/assets/icons/shield-check-20.svg?react";
import Streak20 from "../../../../packages/assets/icons/streak-20.svg?react";
import Timer16 from "../../../../packages/assets/icons/timer-16.svg?react";
import TrendingDown14 from "../../../../packages/assets/icons/trending-down-14.svg?react";
import TrendingUp14 from "../../../../packages/assets/icons/trending-up-14.svg?react";
import Trophy16 from "../../../../packages/assets/icons/trophy-16.svg?react";
import User16 from "../../../../packages/assets/icons/user-16.svg?react";
import User17 from "../../../../packages/assets/icons/user-17.svg?react";
import User20 from "../../../../packages/assets/icons/user-20.svg?react";
import User22 from "../../../../packages/assets/icons/user-22.svg?react";
import Walk18 from "../../../../packages/assets/icons/walk-18.svg?react";
import Walk20 from "../../../../packages/assets/icons/walk-20.svg?react";

export const ICONS = {
  "appointments-16": Appointments16,
  "appointments-18": Appointments18,
  "appointments-20": Appointments20,
  "appointments-22": Appointments22,
  "bike-18": Bike18,
  "bike-20": Bike20,
  "check-14": Check14,
  "check-16": Check16,
  "chevron-left-16": ChevronLeft16,
  "chevron-left-17": ChevronLeft17,
  "chevron-right-16": ChevronRight16,
  "chevron-right-18": ChevronRight18,
  "clock-16": Clock16,
  "clock-20": Clock20,
  "dashboard-18": Dashboard18,
  "devices-16": Devices16,
  "devices-18": Devices18,
  "devices-20": Devices20,
  "devices-22": Devices22,
  "download-16": Download16,
  "droplet-18": Droplet18,
  "droplet-20": Droplet20,
  "droplet-22": Droplet22,
  "dumbbell-16": Dumbbell16,
  "dumbbell-18": Dumbbell18,
  "dumbbell-20": Dumbbell20,
  "dumbbell-22": Dumbbell22,
  "emergency-16": Emergency16,
  "emergency-18": Emergency18,
  "emergency-20": Emergency20,
  "emergency-22": Emergency22,
  "emergency-26": Emergency26,
  "emergency-28": Emergency28,
  "emergency-36": Emergency36,
  "eye-17": Eye17,
  "eye-18": Eye18,
  "family-16": Family16,
  "family-18": Family18,
  "family-20": Family20,
  "family-22": Family22,
  "file-text-16": FileText16,
  "file-text-18": FileText18,
  "file-text-20": FileText20,
  "flame-16": Flame16,
  "goals-16": Goals16,
  "goals-18": Goals18,
  "goals-20": Goals20,
  "health-16": Health16,
  "health-17": Health17,
  "health-18": Health18,
  "health-20": Health20,
  "health-22": Health22,
  "help-18": Help18,
  "home-22": Home22,
  "library-16": Library16,
  "library-18": Library18,
  "library-20": Library20,
  "map-pin-16": MapPin16,
  "medications-16": Medications16,
  "medications-18": Medications18,
  "medications-20": Medications20,
  "medications-22": Medications22,
  "messages-16": Messages16,
  "messages-18": Messages18,
  "messages-20": Messages20,
  "monitor-18": Monitor18,
  "monitor-20": Monitor20,
  "monitor-22": Monitor22,
  "moon-16": Moon16,
  "moon-18": Moon18,
  "notifications-16": Notifications16,
  "notifications-18": Notifications18,
  "notifications-20": Notifications20,
  "nutrition-16": Nutrition16,
  "nutrition-18": Nutrition18,
  "nutrition-20": Nutrition20,
  "phone-16": Phone16,
  "plus-16": Plus16,
  "plus-18": Plus18,
  "print-16": Print16,
  "privacy-16": Privacy16,
  "privacy-18": Privacy18,
  "privacy-20": Privacy20,
  "privacy-22": Privacy22,
  "records-16": Records16,
  "records-18": Records18,
  "records-20": Records20,
  "records-22": Records22,
  "run-18": Run18,
  "run-20": Run20,
  "scale-16": Scale16,
  "scale-18": Scale18,
  "scale-20": Scale20,
  "scale-22": Scale22,
  "search-16": Search16,
  "search-17": Search17,
  "search-18": Search18,
  "settings-16": Settings16,
  "settings-18": Settings18,
  "settings-20": Settings20,
  "share-16": Share16,
  "shield-check-16": ShieldCheck16,
  "shield-check-20": ShieldCheck20,
  "streak-20": Streak20,
  "timer-16": Timer16,
  "trending-down-14": TrendingDown14,
  "trending-up-14": TrendingUp14,
  "trophy-16": Trophy16,
  "user-16": User16,
  "user-17": User17,
  "user-20": User20,
  "user-22": User22,
  "walk-18": Walk18,
  "walk-20": Walk20,
};
