// Same exported Figma SVGs as web (packages/assets/icons). Strokes are
// currentColor, so react-native-svg's `color` prop tints them.
// The registry is generated by scripts/write-icons.py.
import type { ColorToken } from "@vitallink/tokens";
import { c } from "../theme";
import { ICONS } from "./icons.gen";

export type IconName = keyof typeof ICONS;

/** `size` scales the icon (keeps aspect); omit to use the exported size. */
export function Icon({ name, color = "iconDefault", size }: { name: IconName; color?: ColorToken; size?: number }) {
  const Svg = ICONS[name];
  const native = Number(name.split("-").pop());
  return <Svg color={c[color]} width={size ?? native} height={size ?? native} />;
}
