// Generate platform token files from figma-variables.json.
//   css/tokens.css     CSS custom properties for the web (light + dark)
//   src/generated.ts   typed values for React Native and shared code
//
// Naming follows the Figma code syntax already set on each variable:
//   color/bg/surface -> --vl-bg-surface   / color.bgSurface
//   spacing/3        -> --vl-spacing-3    / space[3]
//   radius/md        -> --vl-radius-md    / radius.md
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const src = JSON.parse(readFileSync(join(here, "figma-variables.json"), "utf8"));

const kebab = (s) => s.replace(/\//g, "-");
const camel = (s) => s.replace(/[/-](\w)/g, (_, c) => c.toUpperCase());

const resolve = (ref) => {
  const v = src.primitives[ref];
  if (!v) throw new Error(`Unknown primitive ${ref}`);
  return v;
};

const modes = { light: {}, dark: {} };
for (const [name, [l, d]] of Object.entries(src.color)) {
  modes.light[name] = resolve(l);
  modes.dark[name] = resolve(d);
}

// rgba() for CSS/RN from #rrggbbaa
const toCss = (hex) => {
  if (hex.length === 9) {
    const n = (i) => parseInt(hex.slice(i, i + 2), 16);
    return `rgba(${n(1)}, ${n(3)}, ${n(5)}, ${+(n(7) / 255).toFixed(3)})`;
  }
  return hex;
};

const weights = { Regular: 400, Medium: 500, "Semi Bold": 600, Bold: 700, Mono: 400 };

const shadowCss = (layers) =>
  layers.map(([x, y, b, s, c]) => `${x}px ${y}px ${b}px ${s}px ${toCss(resolve(c))}`).join(", ");

// ---------- CSS ----------
const cssVars = (map) =>
  Object.entries(map).map(([k, v]) => `  --vl-${kebab(k)}: ${toCss(v)};`).join("\n");

const dimVars = Object.entries(src.dimension)
  .map(([k, v]) => `  --vl-${kebab(k)}: ${v}px;`)
  .join("\n");

const elevationVars = Object.entries(src.elevation)
  .map(([k, layers]) => `  --vl-elevation-${k}: ${shadowCss(layers)};`)
  .join("\n");

const textClasses = Object.entries(src.textStyles)
  .map(([k, [w, size, lh, ls]]) => {
    const family = w === "Mono" ? "var(--vl-font-mono)" : "var(--vl-font-sans)";
    return `.vl-${k} { font-family: ${family}; font-weight: ${weights[w]}; font-size: ${size}px; line-height: ${lh}px; letter-spacing: ${ls}px; }`;
  })
  .join("\n");

const css = `/* Generated by packages/tokens/build.mjs from Figma variables. Do not edit. */
:root {
  --vl-font-sans: "Inter", system-ui, -apple-system, "Segoe UI", sans-serif;
  --vl-font-mono: "Roboto Mono", ui-monospace, monospace;
${cssVars(modes.light)}
${dimVars}
${elevationVars}
  color-scheme: light;
}
:root[data-theme="dark"] {
${cssVars(modes.dark)}
  color-scheme: dark;
}
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${cssVars(modes.dark).replace(/^/gm, "  ")}
    color-scheme: dark;
  }
}
/* Pin a subtree to one mode whatever the page theme (e.g. theme previews). */
.vl-light {
${cssVars(modes.light)}
}
.vl-dark {
${cssVars(modes.dark)}
}
${textClasses}
`;

// ---------- TS ----------
const colorObj = (map) =>
  "{\n" + Object.entries(map).map(([k, v]) => `    ${camel(k)}: "${toCss(v)}",`).join("\n") + "\n  }";

const groups = {};
for (const [k, v] of Object.entries(src.dimension)) {
  const [g, n] = k.split("/");
  (groups[g] ??= {})[n] = v;
}

const textTs = Object.entries(src.textStyles)
  .map(([k, [w, size, lh, ls]]) =>
    `  ${camel(k)}: { fontFamily: "${w === "Mono" ? "RobotoMono" : "Inter"}", fontWeight: "${weights[w]}", fontSize: ${size}, lineHeight: ${lh}, letterSpacing: ${ls} },`)
  .join("\n");

const elevationTs = Object.entries(src.elevation)
  .map(([k, layers]) => `  ${k}: ${JSON.stringify(shadowCss(layers))},`)
  .join("\n");

const ts = `// Generated by packages/tokens/build.mjs from Figma variables. Do not edit.
export const colors = {
  light: ${colorObj(modes.light)},
  dark: ${colorObj(modes.dark)},
} as const;

export type ColorToken = keyof typeof colors.light;
export type ColorScheme = keyof typeof colors;

export const space = ${JSON.stringify(groups.spacing)} as const;
export const radius = ${JSON.stringify(groups.radius)} as const;
export const border = ${JSON.stringify(groups.border)} as const;
export const size = ${JSON.stringify(groups.size)} as const;
export const layout = ${JSON.stringify(groups.layout)} as const;

export const text = {
${textTs}
} as const;

export type TextStyle = keyof typeof text;

/** CSS box-shadow strings; React Native 0.76+ accepts these via boxShadow. */
export const elevation = {
${elevationTs}
} as const;
`;

mkdirSync(join(here, "css"), { recursive: true });
mkdirSync(join(here, "src"), { recursive: true });
writeFileSync(join(here, "css", "tokens.css"), css);
writeFileSync(join(here, "src", "generated.ts"), ts);
console.log(
  `tokens: ${Object.keys(src.color).length} colours x2 modes, ${Object.keys(src.dimension).length} dimensions, ${Object.keys(src.textStyles).length} text styles`,
);
